CREATE TABLE MLPCOMMENT(
	COMMENTNO NUMBER PRIMARY KEY,
	FEEDNO NUMBER NOT NULL,
	WRITER VARCHAR2(500) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	FOREIGN KEY(FEEDNO) REFERENCES MLPFEED(FEEDNO)
);

CREATE SEQUENCE SEQ_MLPCOMMENT NOCACHE;

SELECT * FROM MLPCOMMENT;

ALTER TABLE MLPCOMMENT ADD PARENTCOMMENTNO NUMBER;

ALTER TABLE MLPCOMMENT MODIFY(PARENTCOMMENTNO INT);
-- NULL일 경우엔 일반 댓글이고, NULL이 아니면 댓글의 대댓글이다.