DROP SEQUENCE SEQ_MLPMEMBER;
DROP TABLE MLPMEMBER;

CREATE SEQUENCE SEQ_MLPMEMBER NOCACHE;

CREATE TABLE MLPMEMBER(
	MEMNO NUMBER PRIMARY KEY,
	MEMGROUP VARCHAR2(1000) NOT NULL,
	MEMDEPART VARCHAR2(1000) NOT NULL,
	MEMNAME VARCHAR2(500) NOT NULL,
	MEMID VARCHAR2(500) NOT NULL UNIQUE,
	MEMPW VARCHAR2(500) NOT NULL,
	MEMEMAIL VARCHAR2(2000) NOT NULL UNIQUE,
	MEMPHONE VARCHAR2(1000) NOT NULL UNIQUE,
	MEMENABLED VARCHAR2(2) NOT NULL CHECK(MEMENABLED IN('Y', 'N'))
);

INSERT INTO MLPMEMBER
VALUES(SEQ_MLPMEMBER.NEXTVAL, 'K-디지털', '[현대이지웰] Java 풀스택 개발자 아카데미 5회차', '관리자', 'ADMIN', 'ADMIN1234', 'multiAdmin@mlp.com', '010-0000-0000', 'Y');

SELECT * FROM MLPMEMBER;