DROP SEQUENCE SEQ_MLPFEED;
DROP TABLE MLPFEED;

CREATE SEQUENCE SEQ_MLPFEED NOCACHE;

CREATE TABLE MLPFEED(
	FEEDNO NUMBER PRIMARY KEY,
	FEEDTITLE VARCHAR2(1000) NOT NULL,
	FEEDCONTENT VARCHAR2(4000) NOT NULL,
	MEMNO NUMBER NOT NULL,
	MEMGROUP VARCHAR2(1000) NOT NULL,
	MEMDEPART VARCHAR2(1000) NOT NULL,
	MEMNAME VARCHAR2(500) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MLPFEED
VALUES(SEQ_MLPFEED.NEXTVAL, '테스트', '피드 작성 테스트 중입니다...', 1, 'K-디지털', '[현대이지웰] Java 풀스택 개발자 아카데미 5회차', '관리자', SYSDATE);

SELECT * FROM MLPFEED;