CREATE TABLE MLPCOMMENT(
	COMMENTNO NUMBER PRIMARY KEY,
	FEEDNO NUMBER NOT NULL,
	WRITER VARCHAR2(500) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	FOREIGN KEY(FEEDNO) REFERENCES MLPFEED(FEEDNO)
);

CREATE SEQUENCE SEQ_MLPCOMMENT NOCACHE;