-- Jsp02_Board
DROP TABLE BOARD;
DROP SEQUENCE SEQ_BOARD;

CREATE SEQUENCE SEQ_BOARD NOCACHE;

CREATE TABLE BOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO BOARD VALUES(SEQ_BOARD.NEXTVAL, '관리자', '테스트 중', 'TEST1234가나다라', SYSDATE);
SELECT * FROM BOARD;



-- Jsp03_MVC
DROP TABLE MVCBOARD;
DROP SEQUENCE SEQ_MVCBOARD;

CREATE SEQUENCE SEQ_MVCBOARD NOCACHE;
CREATE TABLE MVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MVCBOARD
VALUES(SEQ_MVCBOARD.NEXTVAL, '관리자', '테스트 중', '테스트 1234 ABCDE', '22/02/22');

SELECT * FROM MVCBOARD;




--------------------------------------------------
-- Jsp04_LoginBoard
DROP TABLE MYMEMBER;
DROP SEQUENCE SEQ_MYMEMBER;

CREATE SEQUENCE SEQ_MYMEMBER NOCACHE;

CREATE TABLE MYMEMBER(
	MYNO NUMBER PRIMARY KEY,
	MYID VARCHAR2(500) NOT NULL UNIQUE,
	MYPW VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(500) NOT NULL,
	MYADDR VARCHAR2(2000),
	MYPHONE VARCHAR2(1000) NOT NULL UNIQUE,
	MYEMAIL VARCHAR2(2000) NOT NULL UNIQUE,
	MYENABLED VARCHAR2(2) NOT NULL CHECK(MYENABLED IN('Y','N')),
	MYROLE VARCHAR2(50) NOT NULL
);

INSERT INTO MYMEMBER
VALUES(SEQ_MYMEMBER.NEXTVAL, 'ADMIN', 'ADMIN1234', '관리자', '관리시 관리구 관리동',
	   '010-1234-5678', 'ADMIN@MYMEMBER.COM', 'Y', 'ADMIN');
SELECT * FROM MYMEMBER;



-------------------------------------------
-- Jsp08_MVC

DROP TABLE MYMVCBOARD;
DROP SEQUENCE SEQ_MYMVCBOARD;

CREATE SEQUENCE SEQ_MYMVCBOARD NOCACHE;

CREATE TABLE MYMVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(200) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MYMVCBOARD
VALUES(SEQ_MYMVCBOARD.NEXTVAL, '관리자', '테스트', '테스트 중입니다. 123', '22/02/22');

SELECT * FROM MYMVCBOARD;


------------------------------------------------------------
-- Jsp09_AnswerBoard

DROP TABLE ANSWERBOARD;
DROP SEQUENCE BOARDNOSQ;
DROP SEQUENCE GROUPNOSQ;

-- 글 번호 시퀀스 (PK)
CREATE SEQUENCE BOARDNOSQ NOCACHE;

-- 그룹 번호 시퀀스
CREATE SEQUENCE GROUPNOSQ NOCACHE;

CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(500) NOT NULL,
	REGDATE DATE NOT NULL
);

SELECT * FROM ANSWERBOARD;

-- 첫번째 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0, '첫번째 글', '1번 글 입니다!!', '유저1', SYSDATE);


-- 두번째 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0, '두번째 글', '2번 글 입니다!!', '유저2', SYSDATE);

-- 답변 글 작성 (1번 글의)
-- 부모(1번 글)와 같은 GROUPNO
-- 부모의 GROUPSQ+1, 부모의 TITLETAB+2
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=1)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=1)+2,
		'RE:첫번째 글', '1번글의 답변 글입니다.','유저2', SYSDATE);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;


-- 세번째 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0, '세번째 글', '3번 글 입니다!!', '유저3', SYSDATE);


-- 답글 작성(두 번째 글)
-- 부모(2번 글)와 같은 GROUPNO
-- 부모의 GROUPSQ+1, 부모의 TITLETAB+2
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+2,
		'RE:두번째 글', '2번글의 답변 글입니다.','유저1', SYSDATE);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;


-- 답글 작성(NO가 5)
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+2,
		'RE:RE:두번째 글', '2번 글 답변 글의 답변 글','유저2', SYSDATE);

-- 답변글 작성(두 번째글- NO가 2)
-- 부모와 같은 GROUPNO에서
-- 부모보다 큰 GROUPSQ 글들을 GROUPSQ+1
UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2)
  AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2);

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+2,
		'RE:두번째 글', '2번 글 답변 글 두번째임','유저3', SYSDATE);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;

-- 답변 작성(NO-7)
--1. UPDATE
-- 부모와 같은 GROUPNO이고 부모의 GROUPSQL보다 큰 글들의
-- GROUPSQ+1

--2. INSERT
-- 부모와 같은 GROUPNO, 부모의 GROUPSQ + 1, 부모의 TITLETAB+2
UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7)
  AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7);

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7),
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=7)+2,
		'R:RE:두번째 글#@#', '2번 글 답변 글의 답글','유저2', SYSDATE);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;


------------------------------------------------------------
-- Jsp10_Async
DROP TABLE BIKE_TB;

CREATE TABLE BIKE_TB(
	ADDR_GU VARCHAR2(4000),
	CONTENT_ID NUMBER PRIMARY KEY,
	CONTENT_NM VARCHAR2(4000),
	NEW_ADDR VARCHAR2(4000),
	CRADLE_COUNT NUMBER,
	LONGITUDE NUMBER,
	LATITUDE NUMBER
);

SELECT * FROM BIKE_TB;
DELETE FROM BIKE_TB;

SELECT * FROM MYBOARD;



----------------------------------------
-- Jsp12_Board_Mybatis
SELECT * FROM BOARD;