-- Jsp02_Board
DROP TABLE BOARD;
DROP SEQUENCE SEQ_BOARD;

CREATE SEQUENCE SEQ_BOARD NOCACHE;

CREATE TABLE BOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO BOARD VALUES(SEQ_BOARD.NEXTVAL, '관리자', '테스트 중', 'TEST1234가나다라', SYSDATE);
SELECT * FROM BOARD;



-- Jsp03_MVC
DROP TABLE MVCBOARD;
DROP SEQUENCE SEQ_MVCBOARD;

CREATE SEQUENCE SEQ_MVCBOARD NOCACHE;
CREATE TABLE MVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MVCBOARD
VALUES(SEQ_MVCBOARD.NEXTVAL, '관리자', '테스트 중', '테스트 1234 ABCDE', '22/02/22');

SELECT * FROM MVCBOARD;




--------------------------------------------------
-- Jsp04_LoginBoard
DROP TABLE MYMEMBER;
DROP SEQUENCE SEQ_MYMEMBER;

CREATE SEQUENCE SEQ_MYMEMBER NOCACHE;

CREATE TABLE MYMEMBER(
	MYNO NUMBER PRIMARY KEY,
	MYID VARCHAR2(500) NOT NULL UNIQUE,
	MYPW VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(500) NOT NULL,
	MYADDR VARCHAR2(2000),
	MYPHONE VARCHAR2(1000) NOT NULL UNIQUE,
	MYEMAIL VARCHAR2(2000) NOT NULL UNIQUE,
	MYENABLED VARCHAR2(2) NOT NULL CHECK(MYENABLED IN('Y','N')),
	MYROLE VARCHAR2(50) NOT NULL
);

INSERT INTO MYMEMBER
VALUES(SEQ_MYMEMBER.NEXTVAL, 'ADMIN', 'ADMIN1234', '관리자', '관리시 관리구 관리동',
	   '010-1234-5678', 'ADMIN@MYMEMBER.COM', 'Y', 'ADMIN');
SELECT * FROM MYMEMBER;