DROP TABLE COMMUNITYMEMBER;
DROP SEQUENCE SEQ_CM;

CREATE SEQUENCE SEQ_CM NOCACHE;

CREATE TABLE COMMUNITYMEMBER(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(500) NOT NULL,
	PW VARCHAR2(500) NOT NULL,
	NAME VARCHAR2(300) NOT NULL,
	PHONE VARCHAR2(1000) NOT NULL,
	ENABLED VARCHAR2(2) NOT NULL CHECK(ENABLED IN('Y','N'))
);

SELECT * FROM COMMUNITYMEMBER;

INSERT INTO COMMUNITYMEMBER
VALUES(SEQ_CM.NEXTVAL, 'ADMIN', 'ADMIN1234', '관리자', '010-1111-2222', 'Y');