DROP TABLE COMMUNITYBOARD;
DROP SEQUENCE SEQ_CB;

CREATE SEQUENCE SEQ_CB NOCACHE;

CREATE TABLE COMMUNITYBOARD(
	NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(300) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

SELECT * FROM COMMUNITYBOARD;

INSERT INTO COMMUNITYBOARD
VALUES(SEQ_CB.NEXTVAL, '관리자', '테스트입니다', '안녕하세요 테스트 중입니다.', SYSDATE);